from Hashmap import Hashmap

hmap = Hashmap()
hmap.createHashmap(1, 15)
hmap.insert(5,5)
hmap.insert(6,6)
hmap.insert(7,7)
hmap.insert(9)
hmap.insert(9)
hmap.erase(7)
hmap.print()
print("end:")
print(hmap.end())
print(hmap.begin())
print(hmap.findByValue(10))
